---
# Fichier .cpanel.yml pour le déploiement Git sur cPanel (o2switch)
# Ce fichier doit être placé à la racine de votre dépôt Git.

deployment:
  # La section tasks contient les commandes shell à exécuter
  # après un push réussi sur la branche configurée pour le déploiement.
  tasks:
    # 1. Créer le répertoire de déploiement s'il n'existe pas.
    #    $DEPLOYPATH est une variable d'environnement définie par cPanel
    - export DEPLOYPATH=/home/bemo1278/public_html/ecotisations.aladints.com
    #    qui pointe vers le répertoire de destination (/home/bemo1278/public_html/ecotisations).
    # - /bin/mkdir -p $DEPLOYPATH
    
    # 2. Copier tous les fichiers et dossiers (sauf .git) du dépôt
    #    vers le répertoire de déploiement.
    #    L'exécution de ces commandes se fait depuis la racine du dépôt.
    - /bin/cp -R * $DEPLOYPATH
    
    # --- COMMANDES DE POST-DÉPLOIEMENT ---
    
    # 3. Mise en maintenance (pour éviter des erreurs pendant la migration)
    - /usr/local/bin/php $DEPLOYPATH/artisan down || true
    
    # 4. Installation des dépendances Composer
    - /usr/local/bin/composer install --no-dev --optimize-autoloader --prefer-dist -d $DEPLOYPATH
    
    # 5. Exécution des migrations (obligatoire pour les nouveaux modules)
    - /usr/local/bin/php $DEPLOYPATH/artisan migrate --force --seed
    
    # 6. Création du lien symbolique de stockage
    - /usr/local/bin/php $DEPLOYPATH/artisan storage:link || true
    
    # 7. Optimisation des performances (Config, Routes et Views)
    - /usr/local/bin/php $DEPLOYPATH/artisan config:cache
    - /usr/local/bin/php $DEPLOYPATH/artisan route:cache
    - /usr/local/bin/php $DEPLOYPATH/artisan view:cache
    
    # 8. Sortie du mode maintenance
    - /usr/local/bin/php $DEPLOYPATH/artisan up
    

    
